# 站点设置
title: 中国性少数历史档案
url: "https://china-lgbtq-archive.github.io"
baseurl: ""

# 构建设置
markdown: kramdown
permalink: /entries/:slug/

# 集合设置
collections:
  entries:
    output: true
    permalink: /entries/:slug/

# 默认值
defaults:
  - scope:
      path: ""
      type: "entries"
    values:
      layout: "entry"

# 排除文件
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock